### ISSUE TITLE
Implement T3D mode validation/picker in eos

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/eos#23]
Eos already does few things in regard to stances:

1) Each time you assign new fit.stance, old one gets removed.
2) You cannot put stance to any other endpoint, endpoints are doing class check when you put items into them. This is example of single-item endpoint doing this, it's the same for multi-item containers: https://github.com/pyfa-org/eos/blob/master/eos/fit/holder/container/single_onfit.py#L48
3) There're some checks which verify if typeID stored within Stance instance is actually stance: https://github.com/pyfa-org/eos/blob/master/eos/fit/restriction_tracker/register/holder_class.py#L69

It doesn't:
1) No checks that this ship can have this stance.

I assume it's the only thing it's not doing. If you have anything to add - please do.

**Comment by DarkFenX** [comment]
Now, to where it should be placed. We have several options:

1) Implementation. It's either hardcoding with IDs or name detection like implemented in pyfa: https://github.com/pyfa-org/Pyfa/blob/master/eos/saveddata/ship.py#L112
2) Where to implement - eos or layers above it.

And additional point: any implementation of validation of stances will collect sufficient data to present list of stances for current ship (which WILL be needed by UI). So we have to consider this functionality too. For some reason i do not feel that this functionality should belong to eos, but validation has to come together with it to keep stuff efficient.

Pick what you like.

Options i like (1st one i like more):
1) group + name detection (like in pyfa) implemented in the layer above the eos
2) hardcoding in eos

**Comment by blitzmann** [comment]
I don't know if I gave my thoughts on this in the pyfa channel or in a private message to someone, but here was my thought:

When eos compiles it's cache, shouldn't it be possible to dynamically create (via an implementation like pyfa has) a mapping between ships and correct stances and store it in the cache? This is kind of the caches purpose - to pre-calculate some of the long-form data that we have and condense it to something that EOS can work with. That way, EOS can handle the validation of the stance like I would think it should do as a fitting engine, and validation is separate from pyfa and the layers above EOS (which is important if we want to expose EOS to third parties - if we allow Amarr stances for the Svipul, we're gonna get bug reports for EOS about it). 

IIRC the cache is comprised of data stores and it seems to me it would be simple to create an extremely small one which will be used for the mapping. But as I continue to say, I don't know enough of the design behind it =P

If it's not feasible to do that, I would still prefer functionality in EOS to handle cases outside of pyfa. Thoughts?

**Comment by DarkFenX** [comment]
yeah it's good option. I considered it long time ago but forgot by now.

**Comment by DarkFenX** [comment]
I propose following approach:

1) Cache generator does the name magic to map stances to ships and store it. Cache handler exposes methods to access this data.
2) Additional enum is created for Eos with defensive, offensive and prop mode
3) We keep fit.stance as-is - for ability to set any stance directly and to read item attribs
4) We add
  - separate enum (eg StanceType with def/att/prop values)
  - add property fit.has_stances
  - add method fit.set_stance_type() which accepts value from forementioned enum

This way UI can check if ship has stances, then use enum to set defensive/attack/propulsion stances.

Quite possibly it will be more complex due to Source management. But on 1st glance it looks ok.

**Comment by Regner** [comment]
> This way UI can check if ship has stances, then use enum to set defensive/attack/propulsion stances.

My concern with that is you then are coupling Eos with the UI. Instead of just the UI tossing fits at Eos and getting a calculated fit back the UI is also using Eos to determine what to render before ever validating a fit.

Don't necessarily have a better option right now though.

The more I think about it I guess that isn't entirely true. It is possible for UIs just to hard code the enums and pass them. So long as we don't go changing them much it is fine.

Took a look at the `__getModeItems()` and by god that is some wicked hackery. Asked CCP Larrikin how they are actually doing it in EVE to see if we are missing something. Hoping there is a better way to detect that.

**Comment by Ebag333** [comment]
>My concern with that is you then are coupling Eos with the UI. Instead of just the UI tossing fits at Eos and getting a calculated fit back the UI is also using Eos to determine what to render before ever validating a fit.

This is my concern as well.

Eos works very well as a data driven dynamic engine.  The more things we hard code and hack into it, the more we get away from that.

If we put this in the context of an entire life cycle of building a fit, I don't think that this validation belongs in Eos.  If it did, the life cycle might look something like this: (And yes, this is extremely simplified and a very high level view)
1. User selects a ship (lets say Svipul).
2. UI asks Eos what stances are valid for the Svipul.  (This could be as simple as running a `fit.validate()` on the empty hull, which is exactly what we'll need to do.)
3. Eos sends back a list.
4. UI displays list of choices to user.
5. User selects the mode.
6. UI sends completed fit to Eos to be calculated.

The problem here is that there's nothing that supports showing what stances are supported by what ship.  All of our other information could come back this way (how many slots, if it has subsystems or not, PG, etc etc etc), but there's nothing for states, nor can there be since only 1 state is allowed (if we automatically built all three in and then selected which one was used, that'd be a different story).

So I don't see a way around having the UI handle the states regardless of what we do.  We can create some tables to hard link modules to states to ships for validation purposes (IE: hey idiot, you sent in the wrong state for this ship), but the UI will have to know about states and handle them outside of Eos entirely.

> Hoping there is a better way to detect that.

I really hope that this is the case.

**Comment by blitzmann** [comment]
> My concern with that is you then are coupling Eos with the UI. Instead of just the UI tossing fits at Eos and getting a calculated fit back the UI is also using Eos to determine what to render before ever validating a fit.

My initial thought to this statement: we're not necessarily coupling EOS with the UI. At least, when I say that, I mean that EOS is not dependant on the UI. EOS needs this data anyway to perform validation of the stances. All we are doing is exposing that data. To me, this is the same as exposing the attribute stats that are calculated. It's more like a property of the fit - it tells you what stances are available for it.

Granted, I see the other side of this argument in that this would be a query against EOS for data, which is something that I don't think it currently does elsewhere. I think that, for the purposes of the UI, this can always be generated separately from EOS on the API / service layer and attached to the fit modal that is sent to the client. So the client can know about the different, valid stances that the user can select from, and EOS can perform the server-side validation of the data.

So ultimately I can see this going either way. But I still think this validation is necessary within EOS, and I agree with pre-processing that data and storing it in the cache to be used during fit calculations. 

>Took a look at the __getModeItems() and by god that is some wicked hackery.
Yeah, it's one of my finer hacks. :D I really hope that there is a better way. From what I remember, CCP hardcoded the mapping of stances to ships in the client.

**Comment by DarkFenX** [comment]
I agree with most of the arguments above. We can implement logic i mentioned in my previous message in a layer above the eos (i was going to hardcode it in pyfa-experimental for example). Eos itself will gladly accept any item from Ship Modifier group as stance, and no additional checks will be done besides those which are already implemented.

Eos being used for picking stance for a given ship also never sounded as a right thing to me.

**Comment by Ebag333** [comment]
>We can implement logic i mentioned in my previous message in a layer above the eos (i was going to hardcode it in pyfa-experimental for example).

This to me makes perfect sense.  The layer/framework/skeleton/pyfa-experimental that has been discussed will have full knowledge of abstract things, like names and access to other data, access to Crest, etc.  We can relatively easily connect things there that we would have to hard code in Eos.

**Comment by DarkFenX** [comment]
As we agreed it doesn't belong to eos, closing this ticket.
